### ISSUE TITLE
Fail to follow "intro" documentation

### ISSUE THREAD

**Issue by JbIPS** [cozy/cozy-docdev-v3#9]
Hi,

I'm trying to follow the [new documentation](https://cozy.github.io/cozy-docdev-v3/fr/intro) and have some issues:
* the command `docker run --rm -it -p 8080:8080 -p 5984:5984 -p 8025:8025 -v $(pwd):/data/cozy-app -v ~/cozy/data/db:/usr/local/couchdb/data -v ~/cozy/data/storage":/data/cozy-storage --name=cozydev cozy/cozy-app-dev` have an unmatched `"` but I supposed it shouldn't be here at all.
* after starting the container, all the endpoint on `:8080` are not responding. Here's the full stack:
```
sudo docker run --rm -it -p 8080:8080 -p 5984:5984 -p 8025:8025 -v $(pwd):/data/cozy-app --name=cozydev cozy/cozy-app-dev

WARNING:
  No manifest.webapp file has been found in the mounted
  directory /data/cozy-app. The stack will be started
  without serving any local application.

checking that :8080 is free... ok
waiting for couchdb...ok
checking couchdb on http://localhost:5984/... ok
starting cozy-stack with /data/cozy-storage...
                           !! DEVELOPMENT RELEASE !!
You are running a development release which may deactivate some very important
security features. Please do not use this binary as your production server.

⇛ http server started on 127.0.0.1:6060
⇛ http server started on [::]:8080
time=2017-05-15T15:26:40Z       status=200      method=GET      host=cozy.tools:8080    uri=/version/   bytes_out=132

creating instance cozy.tools:8080 using passphrase "cozy"... ok
creating instance localhost:8080 using passphrase "cozy"... ok
To exit, press ^C
ERRO[0030] [http] GET / Instance not found
time=2017-05-15T15:27:10Z       status=500      method=GET      host=app.cozy.local:8080        uri=/   bytes_out=100
ERRO[0033] [http] GET / Instance not found
time=2017-05-15T15:27:13Z       status=500      method=GET      host=app.cozy.local:8080        uri=/   bytes_out=100
ERRO[0204] [http] GET / Instance not found
time=2017-05-15T15:30:04Z       status=500      method=GET      host=cozy.local:8080    uri=/   bytes_out=100
ERRO[0218] [http] GET / Instance not found
time=2017-05-15T15:30:18Z       status=500      method=GET      host=cozy.local:8080    uri=/   bytes_out=100
```
I suppose the warning is the key here, but I'm in the clone app template and **do** havea `manifest.webapp` in `$pwd`.

And just to get a better grasp with the subdomains, the cloned template is in a directory called `myapp` but the domain is `app.cozy.local`. Where is this defined?

Thank you

**Comment by clochix** [comment]
Hello @JbIPS, 

> unmatched "

Nice catch, I'll fix this ☺

Regarding your issue, I must admit I don't understand what's going on. Could you try again using the full path of the folder where your `manifest.webapp` leaves, instead of `$(pwd)`. Also, could you check its permissions?

**Comment by nono** [comment]
The instance is created for the domain `cozy.tools:8080` (and its subdomains), but the requests are made for `cozy.local:8080`.

**Comment by JbIPS** [comment]
> The instance is created for the domain cozy.tools:8080 (and its subdomains), but the requests are made for cozy.local:8080.

Thank you @nono, that was it, I don't know which name should be kept but be sure it's the same between the doc and the image 😉.

For the manifest problem I tried with the full path and it worked **IF** it ends with a `/`. And today I learned that `pwd` didn't...

**Comment by nono** [comment]
It's `cozy.tools:8080` that will be kept. We should update the docs for both the domain and the trailing slash issue.

**Comment by JbIPS** [comment]
Thank you, see you in v3!
